name: plan-apply

on:
  pull_request: { branches: [main] }
  push:         { branches: [main] }

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/terraform
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region:     ${{ secrets.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init -reconfigure

      - run: terraform workspace select dev || terraform workspace new dev

      - if: github.event_name == 'pull_request'
        run: terraform plan -var-file="environments/dev/dev.tfvars"

      - if: github.event_name == 'push'
        run: terraform apply -auto-approve -var-file="environments/dev/dev.tfvars"
