name: Deploy — Terraform plan & apply

on:
  push:
    branches: [main]
    paths:
      - "infra/terraform/**"
      - "environments/**"
      - ".github/workflows/plan_apply.yml"
  pull_request:
    branches: [main]
    paths:
      - "infra/terraform/**"
      - "environments/**"
      - ".github/workflows/plan_apply.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION:     ${{ secrets.AWS_REGION }}
  TF_WORKING_DIR: infra/terraform
  TF_WORKSPACE:   dev

jobs:
  plan-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (deploy repo)
        uses: actions/checkout@v4

      # Preflight: validate the role ARN secret format before trying OIDC
      - name: Validate AWS_TF_DEPLOY_ROLE secret format
        run: |
          if [ -z "${{ secrets.AWS_TF_DEPLOY_ROLE }}" ]; then
            echo "ERROR: AWS_TF_DEPLOY_ROLE secret is empty or undefined."; exit 1
          fi
          ARN='${{ secrets.AWS_TF_DEPLOY_ROLE }}'
          case "$ARN" in
            arn:aws:iam::*:role/*) echo "Role ARN format looks OK."; ;;
            *) echo "ERROR: AWS_TF_DEPLOY_ROLE is not a valid IAM role ARN: $ARN"; exit 1 ;;
          esac

      # Assume role via OIDC (directly from secret)
      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_TF_DEPLOY_ROLE }}
          role-session-name: tf-deploy
          audience: sts.amazonaws.com
          output-env-credentials: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -input=false

      - name: Show active workspace (from env)
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          TF_WORKSPACE: ${{ env.TF_WORKSPACE }}
        run: |
          echo "TF_WORKSPACE=$TF_WORKSPACE"
          terraform workspace show

      - name: Fmt & Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform fmt -recursive
          terraform validate

      - name: Plan (dev)
        id: plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform plan \
            -var-file="../../environments/dev/dev.tfvars" \
            -var-file="../../environments/dev/app.auto.tfvars" \
            -out=tfplan

      - name: Upload plan artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ${{ env.TF_WORKING_DIR }}/tfplan

      - name: Apply (dev)
        if: github.event_name == 'push'
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve tfplan

