name: Deploy - Terraform Plan & Apply

on:
  pull_request:
    branches: [main]
    paths:
      - "infra/terraform/**"
      - ".github/workflows/plan_apply.yml"
  push:
    branches: [main]
    paths:
      - "infra/terraform/**"
      - ".github/workflows/plan_apply.yml"
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  TF_WORKDIR: infra/terraform
  TF_VARS: environments/dev/dev.tfvars
  TF_IN_AUTOMATION: "true"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_WORKDIR }}
    concurrency:
      group: deploy-terraform
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          output-credentials: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform init (reconfigure backend)
        run: terraform init -input=false -reconfigure

      # One-off: prove CI can see the exact subnets defined in tfvars
      - name: Debug ALB networking (one-off)
        run: |
          set -euo pipefail
          echo "Region: ${{ env.AWS_REGION }}"
          echo "Using tfvars:"
          sed -n '1,120p' "${{ env.TF_VARS }}"
          echo "--- Check subnets from same role/region ---"
          SUBNETS=$(grep -E '^\s*alb_subnet_ids' -n "${{ env.TF_VARS }}" | sed -E 's/.*\[(.*)\].*/\1/' | tr -d '"' | tr ',' ' ')
          echo "Parsed subnets from tfvars: $SUBNETS"
          aws ec2 describe-subnets --subnet-ids $SUBNETS --query 'Subnets[].SubnetId' --output text

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Terraform validate
        run: terraform validate

      # Create if missing (ignore "already exists"), then select
      - name: Terraform workspace (ensure dev)
        run: |
          set -e
          terraform workspace new dev >/dev/null 2>&1 || true
          terraform workspace select dev
          terraform workspace show

      # Visibility: prove TG exists in remote 'dev' state
      - name: Show TG in state (dev)
        run: |
          set -e
          terraform state list | grep -E '^module\.alb\.aws_lb_target_group\.app$' || true
          terraform state show -no-color module.alb.aws_lb_target_group.app | sed -n 's/^\s*id\s*=\s*//p' || true

      - name: Terraform plan
        if: github.event_name == 'pull_request'
        run: |
          set -e
          terraform plan -input=false -no-color -compact-warnings -var-file="${{ env.TF_VARS }}" | tee plan.out.txt

      - name: Comment plan on PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: infra/terraform/plan.out.txt
        env:
          GITHUB_TOKEN: ${{ github.token }}
        continue-on-error: true

      - name: Terraform apply
        if: github.event_name == 'push'
        run: terraform apply -input=false -auto-approve -var-file="${{ env.TF_VARS }}"
