name: Deploy — Terraform plan & apply

on:
  push:
    branches: [main]
    paths:
      - "infra/terraform/**"
      - "environments/**"
      - ".github/workflows/plan_apply.yml"
  pull_request:
    branches: [main]
    paths:
      - "infra/terraform/**"
      - "environments/**"
      - ".github/workflows/plan_apply.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION:     ${{ secrets.AWS_REGION }}
  TF_WORKING_DIR: infra/terraform
  TF_WORKSPACE:   dev
  TF_VARS:        ../environments/dev/dev.tfvars
  TF_VARS_DIGEST: ../environments/dev/app.auto.tfvars   # <- add this

jobs:
  plan-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (deploy repo)
        uses: actions/checkout@v4

      - name: Validate AWS_TF_DEPLOY_ROLE secret format
        run: |
          if [ -z "${{ secrets.AWS_TF_DEPLOY_ROLE }}" ]; then
            echo "ERROR: AWS_TF_DEPLOY_ROLE secret is empty or undefined."; exit 1
          fi
          ARN='${{ secrets.AWS_TF_DEPLOY_ROLE }}'
          case "$ARN" in
            arn:aws:iam::*:role/*) echo "Role ARN format looks OK." ;;
            *) echo "ERROR: AWS_TF_DEPLOY_ROLE is not a valid IAM role ARN: $ARN"; exit 1 ;;
          esac

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_TF_DEPLOY_ROLE }}
          role-session-name: tf-deploy
          audience: sts.amazonaws.com
          output-env-credentials: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.13.3'

      - name: Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -input=false

      - name: Verify var files exist
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          echo "PWD: $(pwd)"
          ls -la
          ls -la environments/dev || true
          ls -la ../environments/dev || true
          test -f "${{ env.TF_VARS }}" && echo "OK: ${{ env.TF_VARS }}" || { echo "MISSING: ${{ env.TF_VARS }}"; exit 1; }
          test -f "${{ env.TF_VARS_DIGEST }}" && echo "OK: ${{ env.TF_VARS_DIGEST }}" || { echo "MISSING: ${{ env.TF_VARS_DIGEST }}"; exit 1; }

      - name: Ensure TG is in state (import if missing)
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          TG_NAME: micro-dev-tg-80
          AWS_REGION: ${{ env.AWS_REGION }}
        run: |
          set -e
          # If the TG isn't in state, import it by name
          if ! terraform state show module.alb.aws_lb_target_group.app > /dev/null 2>&1; then
            TG_ARN=$(aws elbv2 describe-target-groups --region "$AWS_REGION" --names "$TG_NAME" --query "TargetGroups[0].TargetGroupArn" --output text)
            echo "Importing TG into state: $TG_ARN"
            terraform import -var-file="${{ env.TF_VARS }}" module.alb.aws_lb_target_group.app "$TG_ARN"
          else
            echo "TG already in state; skipping import."
          fi

      - name: Show active workspace (from env)
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          TF_WORKSPACE: ${{ env.TF_WORKSPACE }}
        run: |
          echo "TF_WORKSPACE=$TF_WORKSPACE"
          terraform workspace show

      - name: Fmt & Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform fmt -recursive
          terraform validate

      - name: Plan (dev)
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -input=false -var-file="${{ env.TF_VARS }}" -var-file="${{ env.TF_VARS_DIGEST }}" -out=tfplan

      - name: Upload plan artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ${{ env.TF_WORKING_DIR }}/tfplan

      - name: Apply (dev)
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve tfplan
