name: Deploy — Terraform plan & apply

on:
  push:
    branches: [main]
    paths:
      - "infra/terraform/**"
      - "environments/**"
      - ".github/workflows/plan_apply.yml"
  pull_request:
    branches: [main]
    paths:
      - "infra/terraform/**"
      - "environments/**"
      - ".github/workflows/plan_apply.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION:     ${{ secrets.AWS_REGION }}
  TF_WORKING_DIR: infra/terraform
  TF_WORKSPACE:   dev
  AWS_REGION:         ${{ secrets.AWS_REGION }}
  AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_TF_DEPLOY_ROLE }}   # e.g. arn:aws:iam::<acct>:role/GitHubTerraformDeployRole
  TF_WORKING_DIR:     infra/terraform
  TF_WORKSPACE:       dev

jobs:
  plan-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (deploy repo)
        uses: actions/checkout@v4

      # Assume role via OIDC (directly from secret)
      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_TF_DEPLOY_ROLE }}   # e.g. arn:aws:iam::<acct>:role/GitHubTerraformDeployRole
          role-session-name: tf-deploy
          audience: sts.amazonaws.com
          output-env-credentials: true
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: tf-deploy

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -input=false

      - name: Select workspace
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform workspace select ${{ env.TF_WORKSPACE }} || terraform workspace new ${{ env.TF_WORKSPACE }}

      - name: Fmt & Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform fmt -recursive
          terraform validate

      - name: Plan (dev)
        id: plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform plan \
            -var-file="../../environments/dev/dev.tfvars" \
            -var-file="../../environments/dev/app.auto.tfvars" \
            -out=tfplan

      # Upload plan on PRs for review
      - name: Upload plan artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ${{ env.TF_WORKING_DIR }}/tfplan

      # Apply only on push to main
      - name: Apply (dev)
        if: github.event_name == 'push'
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve tfplan
